// const base = '/grupo05sc/public';
const base = '';
export default {
    home: base + '/home',
    rol_index: base + '/rol/index',
    rol_create: base + '/rol/create',
    permiso_index: base + '/permiso/index',
    permiso_create: base + '/permiso/create',
    usuario_index: base + '/usuario/index',
    usuario_create: base + '/usuario/create',
    unidad_medida_index: base + '/unidad_medida/index',
    unidad_medida_create: base + '/unidad_medida/create',
    insumo_index: base + '/insumo/index',
    insumo_create: base + '/insumo/create',
    producto_terminado_index: base + '/producto_terminado/index',
    producto_terminado_create: base + '/producto_terminado/create',
    combo_index: base + '/combo/index',
    combo_create: base + '/combo/create',
    cliente_index: base + '/cliente/index',
    cliente_create: base + '/cliente/create',
    venta_index: base + '/venta/index',
    venta_create: base + '/venta/create',
    reporte_venta_index: base + '/reporte_venta/index',
    pedido_cliente_index: base + '/pedido_cliente/index',
    pedido_cliente_create: base + '/pedido_cliente/create',
}