
const base = '/grupo05sc/public';
// const base = '';
export default {
    login: base + '/api/login',
    modulos: base + '/api/user/modulos',
    set_visitas: base + '/api/setVisitas',
    get_visitas: base + '/api/getVisitas',
    insumo_index: base + '/api/insumo/index',
    insumo_create: base + '/api/insumo/create',
    insumo_store: base + '/api/insumo/store',
    unidad_medida_index: base + '/api/unidad_medida/index',
    unidad_medida_store: base + '/api/unidad_medida/store',
    combo_index: base + '/api/combo/index',
    combo_create: base + '/api/combo/create',
    combo_store: base + '/api/combo/store',
    producto_index: base + '/api/producto/index',
    producto_create: base + '/api/producto/create',
    producto_store: base + '/api/producto/store',
    reporte_venta: base + '/api/venta/reporte',
    permiso_index: base + '/api/permiso/index',
    // permiso_create: base + '',
    permiso_store: base + '/api/permiso/store',
    rol_index: base + '/api/rol/index',
    rol_store: base + '/api/rol/store',
    usuario_index: base + '/api/usuario/index',
    usuario_create: base + '/api/usuario/create',
    usuario_store: base + '/api/usuario/store',
    cliente_index: base + '/api/cliente/index',
    cliente_store: base + '/api/cliente/store',
    venta_index: base + '/api/venta/index',
    venta_create: base + '/api/venta/create',
    venta_store: base + '/api/venta/store',
    usuario_updateconfig: base + '/api/user/updateConfig',
    pedido_cliente_index: base + '/api/pedidocliente',
    pedido_cliente_create: base + '/api/pedidocliente/create',
    pedido_cliente_store: base + '/api/pedidocliente',
    pedido_cliente_edit: base + '/api/pedidocliente',
    pedido_cliente_update: base + '/api/pedidocliente',
    pedido_cliente_delete: base + '/api/pedidocliente',
    estadistica: base + '/api/estadisticas',

}